FROM python:3.10-slim

COPY . /price_app

WORKDIR /price_app

RUN pip3 install --no-cache-dir -r requirements.txt

EXPOSE ${MAIN_APP_PORT}

CMD uvicorn ml_service.price_prediction_app:app --port ${MAIN_APP_PORT} --host 0.0.0.0
